import { NAME } from './constants';

const types = {
  TOGGLE_LINK: `${NAME}/TOGGLE_LINK`,
  OPEN_NODE: `${NAME}/OPEN_NODE`,
  FOCUS: `${NAME}/FOCUS`,
  CYCLE_UP: `${NAME}/CYCLE_UP`,
  CYCLE_DOWN: `${NAME}/CYCLE_DOWN`,
  SHIFT_UP: `${NAME}/SHIFT_UP`,
  SHIFT_DOWN: `${NAME}/SHIFT_DOWN`,
  SLIDE_RIGHT: `${NAME}/SLIDE_RIGHT`,
  SLIDE_LEFT: `${NAME}/SLIDE_LEFT`,
  SLIDE_UP: `${NAME}/SLIDE_UP`,
  SLIDE_DOWN: `${NAME}/SLIDE_DOWN`,
  REFOCUS: `${NAME}/REFOCUS`,
  SET_VISIBLE_COLUMNS: `${NAME}/SET_VISIBLE_COLUMNS`,
};

export default types;
