import { NAME } from './constants'

const types = {
  TOGGLE_LINK: `${NAME}/TOGGLE_LINK`,
  OPEN_NODE: `${NAME}/OPEN_NODE`,
  FOCUS: `${NAME}/FOCUS`,
  CYCLE_UP: `${NAME}/CYCLE_UP`,
  CYCLE_DOWN: `${NAME}/CYCLE_DOWN`,
  SHIFT_UP: `${NAME}/SHIFT_UP`,
  SHIFT_DOWN: `${NAME}/SHIFT_DOWN`,
  SLIDE_RIGHT: `${NAME}/SLIDE_RIGHT`,
  SLIDE_LEFT: `${NAME}/SLIDE_LEFT`,
  SLIDE_UP: `${NAME}/SLIDE_UP`,
  SLIDE_DOWN: `${NAME}/SLIDE_DOWN`,
  REFOCUS: `${NAME}/REFOCUS`,
  ONE_COLUMN: `${NAME}/ONE_COLUMN`,
  TWO_COLUMN: `${NAME}/TWO_COLUMN`,
  THREE_COLUMN: `${NAME}/THREE_COLUMN`,
  FOUR_COLUMN: `${NAME}/FOUR_COLUMN`,
}

export default types
